name: carcassonne # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.8' # just for humans, typically '1.2+git' or '1.3.2'
summary:  Multiplayer version of Carcassonne
description: |
   Multiplayer version of Carcassonne

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  carcassonne_icon.png
title: Carcassonne

apps:
  carcassonne:
    command: startcarcassonne
parts:
  carcassonne:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      carcassonne: build/
      carcassonne.1: man/man1/

architectures:
  - build-on: amd64

